// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: service_manager.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceManager_RegisterServiceNode_FullMethodName   = "/service_manager.ServiceManager/RegisterServiceNode"
	ServiceManager_RequestServiceToken_FullMethodName   = "/service_manager.ServiceManager/RequestServiceToken"
	ServiceManager_RefreshServiceSecret_FullMethodName  = "/service_manager.ServiceManager/RefreshServiceSecret"
	ServiceManager_QueryTokenAndNodeList_FullMethodName = "/service_manager.ServiceManager/QueryTokenAndNodeList"
)

// ServiceManagerClient is the client API for ServiceManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 服务管理器服务
type ServiceManagerClient interface {
	RegisterServiceNode(ctx context.Context, in *RegisterServiceNodeRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	RequestServiceToken(ctx context.Context, in *RequestServiceTokenRequest, opts ...grpc.CallOption) (*RequestServiceTokenResponse, error)
	RefreshServiceSecret(ctx context.Context, in *RefreshServiceSecretRequest, opts ...grpc.CallOption) (*RefreshServiceSecretResponse, error)
	QueryTokenAndNodeList(ctx context.Context, in *RefreshServiceSecretRequest, opts ...grpc.CallOption) (*QueryTokenAndNodeListResponse, error)
}

type serviceManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceManagerClient(cc grpc.ClientConnInterface) ServiceManagerClient {
	return &serviceManagerClient{cc}
}

func (c *serviceManagerClient) RegisterServiceNode(ctx context.Context, in *RegisterServiceNodeRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, ServiceManager_RegisterServiceNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) RequestServiceToken(ctx context.Context, in *RequestServiceTokenRequest, opts ...grpc.CallOption) (*RequestServiceTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestServiceTokenResponse)
	err := c.cc.Invoke(ctx, ServiceManager_RequestServiceToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) RefreshServiceSecret(ctx context.Context, in *RefreshServiceSecretRequest, opts ...grpc.CallOption) (*RefreshServiceSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshServiceSecretResponse)
	err := c.cc.Invoke(ctx, ServiceManager_RefreshServiceSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceManagerClient) QueryTokenAndNodeList(ctx context.Context, in *RefreshServiceSecretRequest, opts ...grpc.CallOption) (*QueryTokenAndNodeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryTokenAndNodeListResponse)
	err := c.cc.Invoke(ctx, ServiceManager_QueryTokenAndNodeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceManagerServer is the server API for ServiceManager service.
// All implementations must embed UnimplementedServiceManagerServer
// for forward compatibility.
//
// 服务管理器服务
type ServiceManagerServer interface {
	RegisterServiceNode(context.Context, *RegisterServiceNodeRequest) (*EmptyResponse, error)
	RequestServiceToken(context.Context, *RequestServiceTokenRequest) (*RequestServiceTokenResponse, error)
	RefreshServiceSecret(context.Context, *RefreshServiceSecretRequest) (*RefreshServiceSecretResponse, error)
	QueryTokenAndNodeList(context.Context, *RefreshServiceSecretRequest) (*QueryTokenAndNodeListResponse, error)
	mustEmbedUnimplementedServiceManagerServer()
}

// UnimplementedServiceManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceManagerServer struct{}

func (UnimplementedServiceManagerServer) RegisterServiceNode(context.Context, *RegisterServiceNodeRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterServiceNode not implemented")
}
func (UnimplementedServiceManagerServer) RequestServiceToken(context.Context, *RequestServiceTokenRequest) (*RequestServiceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestServiceToken not implemented")
}
func (UnimplementedServiceManagerServer) RefreshServiceSecret(context.Context, *RefreshServiceSecretRequest) (*RefreshServiceSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshServiceSecret not implemented")
}
func (UnimplementedServiceManagerServer) QueryTokenAndNodeList(context.Context, *RefreshServiceSecretRequest) (*QueryTokenAndNodeListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryTokenAndNodeList not implemented")
}
func (UnimplementedServiceManagerServer) mustEmbedUnimplementedServiceManagerServer() {}
func (UnimplementedServiceManagerServer) testEmbeddedByValue()                        {}

// UnsafeServiceManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceManagerServer will
// result in compilation errors.
type UnsafeServiceManagerServer interface {
	mustEmbedUnimplementedServiceManagerServer()
}

func RegisterServiceManagerServer(s grpc.ServiceRegistrar, srv ServiceManagerServer) {
	// If the following call pancis, it indicates UnimplementedServiceManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceManager_ServiceDesc, srv)
}

func _ServiceManager_RegisterServiceNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterServiceNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).RegisterServiceNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManager_RegisterServiceNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).RegisterServiceNode(ctx, req.(*RegisterServiceNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_RequestServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).RequestServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManager_RequestServiceToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).RequestServiceToken(ctx, req.(*RequestServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_RefreshServiceSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshServiceSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).RefreshServiceSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManager_RefreshServiceSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).RefreshServiceSecret(ctx, req.(*RefreshServiceSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceManager_QueryTokenAndNodeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshServiceSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceManagerServer).QueryTokenAndNodeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceManager_QueryTokenAndNodeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceManagerServer).QueryTokenAndNodeList(ctx, req.(*RefreshServiceSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceManager_ServiceDesc is the grpc.ServiceDesc for ServiceManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service_manager.ServiceManager",
	HandlerType: (*ServiceManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterServiceNode",
			Handler:    _ServiceManager_RegisterServiceNode_Handler,
		},
		{
			MethodName: "RequestServiceToken",
			Handler:    _ServiceManager_RequestServiceToken_Handler,
		},
		{
			MethodName: "RefreshServiceSecret",
			Handler:    _ServiceManager_RefreshServiceSecret_Handler,
		},
		{
			MethodName: "QueryTokenAndNodeList",
			Handler:    _ServiceManager_QueryTokenAndNodeList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_manager.proto",
}
