// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: service_manager.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	RequestKey    *string                `protobuf:"bytes,2,opt,name=request_key,json=requestKey,proto3,oneof" json:"request_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestService) Reset() {
	*x = RequestService{}
	mi := &file_service_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestService) ProtoMessage() {}

func (x *RequestService) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestService.ProtoReflect.Descriptor instead.
func (*RequestService) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{0}
}

func (x *RequestService) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RequestService) GetRequestKey() string {
	if x != nil && x.RequestKey != nil {
		return *x.RequestKey
	}
	return ""
}

type RegisterServiceNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	App           *RequestService        `protobuf:"bytes,1,opt,name=app,proto3" json:"app,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeIp        string                 `protobuf:"bytes,4,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	ServiceName   string                 `protobuf:"bytes,5,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceType   int32                  `protobuf:"varint,6,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	Port          int32                  `protobuf:"varint,7,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServiceNodeRequest) Reset() {
	*x = RegisterServiceNodeRequest{}
	mi := &file_service_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServiceNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServiceNodeRequest) ProtoMessage() {}

func (x *RegisterServiceNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServiceNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterServiceNodeRequest) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServiceNodeRequest) GetApp() *RequestService {
	if x != nil {
		return x.App
	}
	return nil
}

func (x *RegisterServiceNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterServiceNodeRequest) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *RegisterServiceNodeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterServiceNodeRequest) GetServiceType() int32 {
	if x != nil {
		return x.ServiceType
	}
	return 0
}

func (x *RegisterServiceNodeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_service_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{2}
}

func (x *EmptyResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmptyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestServiceTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerApp     *RequestService        `protobuf:"bytes,1,opt,name=caller_app,json=callerApp,proto3" json:"caller_app,omitempty"`
	CalleeAppId   string                 `protobuf:"bytes,2,opt,name=callee_app_id,json=calleeAppId,proto3" json:"callee_app_id,omitempty"`
	ServiceName   string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestServiceTokenRequest) Reset() {
	*x = RequestServiceTokenRequest{}
	mi := &file_service_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestServiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestServiceTokenRequest) ProtoMessage() {}

func (x *RequestServiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestServiceTokenRequest.ProtoReflect.Descriptor instead.
func (*RequestServiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{3}
}

func (x *RequestServiceTokenRequest) GetCallerApp() *RequestService {
	if x != nil {
		return x.CallerApp
	}
	return nil
}

func (x *RequestServiceTokenRequest) GetCalleeAppId() string {
	if x != nil {
		return x.CalleeAppId
	}
	return ""
}

func (x *RequestServiceTokenRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type RequestServiceTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestServiceTokenResponse) Reset() {
	*x = RequestServiceTokenResponse{}
	mi := &file_service_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestServiceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestServiceTokenResponse) ProtoMessage() {}

func (x *RequestServiceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestServiceTokenResponse.ProtoReflect.Descriptor instead.
func (*RequestServiceTokenResponse) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{4}
}

func (x *RequestServiceTokenResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RequestServiceTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestServiceTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RefreshServiceSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerApp     *RequestService        `protobuf:"bytes,1,opt,name=caller_app,json=callerApp,proto3" json:"caller_app,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceType   int32                  `protobuf:"varint,3,opt,name=service_type,json=serviceType,proto3" json:"service_type,omitempty"`
	SecretId      string                 `protobuf:"bytes,4,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshServiceSecretRequest) Reset() {
	*x = RefreshServiceSecretRequest{}
	mi := &file_service_manager_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshServiceSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshServiceSecretRequest) ProtoMessage() {}

func (x *RefreshServiceSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshServiceSecretRequest.ProtoReflect.Descriptor instead.
func (*RefreshServiceSecretRequest) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshServiceSecretRequest) GetCallerApp() *RequestService {
	if x != nil {
		return x.CallerApp
	}
	return nil
}

func (x *RefreshServiceSecretRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RefreshServiceSecretRequest) GetServiceType() int32 {
	if x != nil {
		return x.ServiceType
	}
	return 0
}

func (x *RefreshServiceSecretRequest) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

type RefreshServiceSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshServiceSecretResponse) Reset() {
	*x = RefreshServiceSecretResponse{}
	mi := &file_service_manager_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshServiceSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshServiceSecretResponse) ProtoMessage() {}

func (x *RefreshServiceSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshServiceSecretResponse.ProtoReflect.Descriptor instead.
func (*RefreshServiceSecretResponse) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{6}
}

func (x *RefreshServiceSecretResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *RefreshServiceSecretResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ServiceNodeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeIp        string                 `protobuf:"bytes,1,opt,name=node_ip,json=nodeIp,proto3" json:"node_ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceNodeItem) Reset() {
	*x = ServiceNodeItem{}
	mi := &file_service_manager_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNodeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNodeItem) ProtoMessage() {}

func (x *ServiceNodeItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNodeItem.ProtoReflect.Descriptor instead.
func (*ServiceNodeItem) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceNodeItem) GetNodeIp() string {
	if x != nil {
		return x.NodeIp
	}
	return ""
}

func (x *ServiceNodeItem) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceNodeItem) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type QueryTokenAndNodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nodes         []*ServiceNodeItem     `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTokenAndNodeListResponse) Reset() {
	*x = QueryTokenAndNodeListResponse{}
	mi := &file_service_manager_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTokenAndNodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTokenAndNodeListResponse) ProtoMessage() {}

func (x *QueryTokenAndNodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_manager_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTokenAndNodeListResponse.ProtoReflect.Descriptor instead.
func (*QueryTokenAndNodeListResponse) Descriptor() ([]byte, []int) {
	return file_service_manager_proto_rawDescGZIP(), []int{8}
}

func (x *QueryTokenAndNodeListResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *QueryTokenAndNodeListResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *QueryTokenAndNodeListResponse) GetNodes() []*ServiceNodeItem {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_service_manager_proto protoreflect.FileDescriptor

const file_service_manager_proto_rawDesc = "" +
	"\n" +
	"\x15service_manager.proto\x12\x0fservice_manager\"]\n" +
	"\x0eRequestService\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12$\n" +
	"\vrequest_key\x18\x02 \x01(\tH\x00R\n" +
	"requestKey\x88\x01\x01B\x0e\n" +
	"\f_request_key\"\xdb\x01\n" +
	"\x1aRegisterServiceNodeRequest\x121\n" +
	"\x03app\x18\x01 \x01(\v2\x1f.service_manager.RequestServiceR\x03app\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x17\n" +
	"\anode_ip\x18\x04 \x01(\tR\x06nodeIp\x12!\n" +
	"\fservice_name\x18\x05 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_type\x18\x06 \x01(\x05R\vserviceType\x12\x12\n" +
	"\x04port\x18\a \x01(\x05R\x04port\"=\n" +
	"\rEmptyResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa3\x01\n" +
	"\x1aRequestServiceTokenRequest\x12>\n" +
	"\n" +
	"caller_app\x18\x01 \x01(\v2\x1f.service_manager.RequestServiceR\tcallerApp\x12\"\n" +
	"\rcallee_app_id\x18\x02 \x01(\tR\vcalleeAppId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\"a\n" +
	"\x1bRequestServiceTokenResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\xc0\x01\n" +
	"\x1bRefreshServiceSecretRequest\x12>\n" +
	"\n" +
	"caller_app\x18\x01 \x01(\v2\x1f.service_manager.RequestServiceR\tcallerApp\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_type\x18\x03 \x01(\x05R\vserviceType\x12\x1b\n" +
	"\tsecret_id\x18\x04 \x01(\tR\bsecretId\"T\n" +
	"\x1cRefreshServiceSecretResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"W\n" +
	"\x0fServiceNodeItem\x12\x17\n" +
	"\anode_ip\x18\x01 \x01(\tR\x06nodeIp\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"\x8d\x01\n" +
	"\x1dQueryTokenAndNodeListResponse\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x126\n" +
	"\x05nodes\x18\x03 \x03(\v2 .service_manager.ServiceNodeItemR\x05nodes2\xd2\x03\n" +
	"\x0eServiceManager\x12b\n" +
	"\x13RegisterServiceNode\x12+.service_manager.RegisterServiceNodeRequest\x1a\x1e.service_manager.EmptyResponse\x12p\n" +
	"\x13RequestServiceToken\x12+.service_manager.RequestServiceTokenRequest\x1a,.service_manager.RequestServiceTokenResponse\x12s\n" +
	"\x14RefreshServiceSecret\x12,.service_manager.RefreshServiceSecretRequest\x1a-.service_manager.RefreshServiceSecretResponse\x12u\n" +
	"\x15QueryTokenAndNodeList\x12,.service_manager.RefreshServiceSecretRequest\x1a..service_manager.QueryTokenAndNodeListResponseB-Z+github.com/yearsyan/service_manager_api/pkgb\x06proto3"

var (
	file_service_manager_proto_rawDescOnce sync.Once
	file_service_manager_proto_rawDescData []byte
)

func file_service_manager_proto_rawDescGZIP() []byte {
	file_service_manager_proto_rawDescOnce.Do(func() {
		file_service_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_manager_proto_rawDesc), len(file_service_manager_proto_rawDesc)))
	})
	return file_service_manager_proto_rawDescData
}

var file_service_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_service_manager_proto_goTypes = []any{
	(*RequestService)(nil),                // 0: service_manager.RequestService
	(*RegisterServiceNodeRequest)(nil),    // 1: service_manager.RegisterServiceNodeRequest
	(*EmptyResponse)(nil),                 // 2: service_manager.EmptyResponse
	(*RequestServiceTokenRequest)(nil),    // 3: service_manager.RequestServiceTokenRequest
	(*RequestServiceTokenResponse)(nil),   // 4: service_manager.RequestServiceTokenResponse
	(*RefreshServiceSecretRequest)(nil),   // 5: service_manager.RefreshServiceSecretRequest
	(*RefreshServiceSecretResponse)(nil),  // 6: service_manager.RefreshServiceSecretResponse
	(*ServiceNodeItem)(nil),               // 7: service_manager.ServiceNodeItem
	(*QueryTokenAndNodeListResponse)(nil), // 8: service_manager.QueryTokenAndNodeListResponse
}
var file_service_manager_proto_depIdxs = []int32{
	0, // 0: service_manager.RegisterServiceNodeRequest.app:type_name -> service_manager.RequestService
	0, // 1: service_manager.RequestServiceTokenRequest.caller_app:type_name -> service_manager.RequestService
	0, // 2: service_manager.RefreshServiceSecretRequest.caller_app:type_name -> service_manager.RequestService
	7, // 3: service_manager.QueryTokenAndNodeListResponse.nodes:type_name -> service_manager.ServiceNodeItem
	1, // 4: service_manager.ServiceManager.RegisterServiceNode:input_type -> service_manager.RegisterServiceNodeRequest
	3, // 5: service_manager.ServiceManager.RequestServiceToken:input_type -> service_manager.RequestServiceTokenRequest
	5, // 6: service_manager.ServiceManager.RefreshServiceSecret:input_type -> service_manager.RefreshServiceSecretRequest
	5, // 7: service_manager.ServiceManager.QueryTokenAndNodeList:input_type -> service_manager.RefreshServiceSecretRequest
	2, // 8: service_manager.ServiceManager.RegisterServiceNode:output_type -> service_manager.EmptyResponse
	4, // 9: service_manager.ServiceManager.RequestServiceToken:output_type -> service_manager.RequestServiceTokenResponse
	6, // 10: service_manager.ServiceManager.RefreshServiceSecret:output_type -> service_manager.RefreshServiceSecretResponse
	8, // 11: service_manager.ServiceManager.QueryTokenAndNodeList:output_type -> service_manager.QueryTokenAndNodeListResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_service_manager_proto_init() }
func file_service_manager_proto_init() {
	if File_service_manager_proto != nil {
		return
	}
	file_service_manager_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_manager_proto_rawDesc), len(file_service_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_manager_proto_goTypes,
		DependencyIndexes: file_service_manager_proto_depIdxs,
		MessageInfos:      file_service_manager_proto_msgTypes,
	}.Build()
	File_service_manager_proto = out.File
	file_service_manager_proto_goTypes = nil
	file_service_manager_proto_depIdxs = nil
}
